# Notes 2: NumPy Intro

NumPy is the foundational python module for scientific computing. This set of notes will walk through the basics with how to use NumPy. Notes are based off of freeCodeCamp's Python NumPy Tutorial for Beginners on YouTube.

NumPy's main idea is that it uses arrays / matricies instead of lists, which compute much faster than lists.

In [214]:
import numpy as np

# Step 1: Initializing Array:

a = np.array([1,2,3])
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [215]:
# Getting the dimension of arrays:

print(a.ndim) # Should be 1, since we have a vector
print(b.ndim) #2 Should be 2, since we have a matrix

# Getting the shapes of arrays:
print(a.shape) # A is a 3-component vector, so it's just (3,)
print(b.shape) # B has 2 rows and 3 columns, so it's (2,3)

# If we wanted to create an array with data of a specific size:
c = np.array([1,2,3],dtype='int16') # Makes integers 16 bit
print(c.dtype) # Shows we have 16 bit integers in array c
print(c.itemsize) # Shows we have a 2 byte size (8 bits = 1 byte)

1
2
(3,)
(2, 3)
int16
2


## Accessing/Changing specific elements/rows/columns/etc.

In [216]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

# Getting a specific element at [row,column]:
print(a[0,0]) # Returns 0
print(a[1,3]) # Returns 11

# Notice how this starts at 0, just like lists

# Negative row notation also works:
print(a[-1,-1]) # Returns 14


1
11
14


In [217]:
# Getting a row:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [218]:
# Getting a column: 
a[:,0]

array([1, 8])

In [219]:
# Fancier slicing [startindex:endindex:stepsize]
a[0,0:6:2] # Gives every other element in first row

array([1, 3, 5])

In [220]:
# Reassignment:

a[0,0] = 100
print(a)

[[100   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14]]


In [221]:
a[1,:] = 3141
print(a)

[[ 100    2    3    4    5    6    7]
 [3141 3141 3141 3141 3141 3141 3141]]


## Initializing Different Arrays

In [222]:
# All 0s
np.zeros((2,3)) # Argument is dimension of array in rows x columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [223]:
# All ones
np.ones(3,) # Vector of all ones

array([1., 1., 1.])

In [224]:
# Any other number
np.full((2,2),1000)

array([[1000, 1000],
       [1000, 1000]])

In [225]:
np.full_like(a, -1) # makes a matrix of all -1 with dimensions like a

array([[-1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1]])

In [226]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [227]:
# Practice initialization from the tutorial video

A = np.ones((5,5))
A[1:-1,1:-1] = 0
A[2,2] = 9
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [228]:
# Alternate solution where you reassign a whole matrix's worth of values:
A = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
A[1:4,1:4] = z
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays. When you type something like a=b, the two arrays now point to the same thing, so when you modify one you modify the other:

In [229]:
# Here, a = b causes them to be modified together
a = np.array([1,2,3])
b = a
b[0] = 10
a

array([10,  2,  3])

In [230]:
# Here, we use copy to avoid that:
a = np.array([1,2,3])
b = a.copy()
b[0] = 10
a

array([1, 2, 3])

## Math : Arithmetic and Linear Algebra

The main idea here is that when you do arithmetic to an array, it does it to all elements. You can also add and multiply arrays and it will go element-wise.

In [231]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [232]:
a+2

array([3, 4, 5])

In [233]:
a ** 2

array([1, 4, 9])

In [234]:
a + b

array([5, 7, 9])

In [235]:
a * b

array([ 4, 10, 18])

In [236]:
# Here, we're taking the sine of every element

np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

With the arithmetic stuff out of the way, let's move on to linear algebra. We'll start by making a 2x3 and a 3x2 matrix:

In [237]:
A = np.ones((2,3))
print(A)
B = np.full((3,2),2)
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [238]:
# To multiply matricies, we use np.matmul:

np.matmul(A,B)

# You can also use the following:

A@B

array([[6., 6.],
       [6., 6.]])

In [239]:
# Be mindful of the order:

np.matmul(B,A)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [240]:
# Determinants:

I = np.identity(2)
np.linalg.det(I)

1.0

In [241]:
# More basic linear algebra examples

A = np.array([[1,2],[3,5]])
v = np.array([1,1])
u = np.array([-1,1])

print(f"Av = {A@v}") # Matrix vector product
print(f"u dot v = {np.dot(u,v)}") # Dot product
print(f"|v| = {np.linalg.norm(v):.3f}") # magnitude
print(f"Rank A = {np.linalg.matrix_rank(A)}") # Rank
print(f"A^3 = {np.linalg.matrix_power(A,3)}") # Powers of a square matrix



Av = [3 8]
u dot v = 0
|v| = 1.414
Rank A = 2
A^3 = [[ 43  74]
 [111 191]]


In [242]:
np.linalg.svd(A) #SVD of A

SVDResult(U=array([[-0.35737275, -0.93396184],
       [-0.93396184,  0.35737275]]), S=array([6.24294338, 0.16018085]), Vh=array([[-0.50605269, -0.86250257],
       [ 0.86250257, -0.50605269]]))

In [243]:
eigenvalues, eigenvectors = np.linalg.eig(A) # Computes eignvalues and eigenvectors
print(eigenvalues)
print(eigenvectors)

[-0.16227766  6.16227766]
[[-0.86460354 -0.36126098]
 [ 0.50245469 -0.93246475]]


In [ ]:
print(np.linalg.eig(A))

EigResult(eigenvalues=array([-0.16227766,  6.16227766]), eigenvectors=array([[-0.86460354, -0.36126098],
       [ 0.50245469, -0.93246475]]))


In [ ]:
# Here we're extracting a particular eigenvalue and eigenvector

evector_1 = eigenvectors[:,0]
evalue_1 = eigenvalues[0]
print(evector_1)
print(evalue_1)

[-0.86460354  0.50245469]
-0.16227766016837908


In [ ]:
# Here's a check it's actually an eigenpair for the matrix:

print(A@evector_1)
print(evalue_1 * evector_1) 

[ 0.14030584 -0.08153717]
[ 0.14030584 -0.08153717]


Be really careful when extracting eigenvectors -- eigenvectors are the columns of the matrix outputted by np.linalg.eig, not the rows. Make sure to index everything appropriately

In [ ]:
# Solving equations with matricies:

np.linalg.solve(A,v) # Solves Ax = b

array([-3.,  2.])

In [ ]:
# To check for stability, you can use the condition number
# Large condition numbers correspond to unstable matricies:

np.linalg.cond(A) # 38 is pretty good, so we're fine with numerical accuracy

38.97434209415055

Below we're using least squares to solve an overdetermined system. The least squares funtion has four outputs.

x is the solution to the system.

Residuals gives you an array of all of the residuals

Rank gives you the rank of the matrix

s gives you the singular values, which tells you how much the solution matters going along different directions. Smaller singular values correspond to more squishing in a direction and greater numerical sensitivity. (The condition number from above is a ratio of singular values)

In [266]:
# Leasy squares:
A = np.array([[1,2],[3,4],[5,6]])
b = np.array([1,2,4])

x, residuals, rank, s = np.linalg.lstsq(A,b)

print(x)
print(residuals)
print(rank)
print(s)

[0.66666667 0.08333333]
[0.16666667]
2
[9.52551809 0.51430058]


C:\Users\benjn\AppData\Local\Temp\ipykernel_14816\1020174248.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(A,b)


## Miscillaneous

In [268]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats) # Finds minimum

1

In [ ]:
np.max(stats) # Finds maximum

6

axis tells you which dimension to collapse in an array. 

axis = 0: goes along rows
axis = 1: goes across columns

So np.min(stats, axis=0) will go along rows and return the minimum value of each column. 

np.min(stats, axis=1) will go along columns and return the minimum value of each row

In [273]:
np.min(stats,axis=1)

array([1, 4])